# SPDX-FileCopyrightText: 2018-2020 CERN.
# SPDX-FileCopyrightText: 2018-2020 RERO.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=invenio_circulation --cov-report=term-missing
testpaths = docs tests invenio_circulation
